name: mplsoccer-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - pandas
  - scipy
  - seaborn
  - sphinx
  - cmasher
  - pyarrow
  - beautifulsoup4
  - lxml
  - setuptools
  - twine
  - pillow
  - pylint
  - sphinx-gallery
  - sphinx_rtd_theme
  - numpydoc
  - wheel
  - pip
  - pip:
      - -e .
      - highlight-text
      - kloppy
      - adjustText
